# ==================================================
# Training Configuration
# ==================================================

project_name: "human_action_recognition"

seed: 42

# ==================================================
# Dataset
# ==================================================

dataset:
  raw_dir: "/content/UCF101"

  processed_frames_dir: "/content/processed/frames"

  processed_sequences_dir: "/content/processed/sequences"

  train_dir: "/content/train"

  val_dir: "/content/val"

  test_dir: "/content/test"

  image_size: 224
  sequence_length: 8
  num_workers: 4
  sequence_stride: 4

  sample_rate: 3
# ==================================================
# Training
# ==================================================

training:
  batch_size: 8

  epochs: 1

  samples_per_epoch: 60000

  mixed_precision: true

  resume_checkpoint: null

  learning_rate: 0.001

  weight_decay: 0.0001

  optimizer: "adam"

  scheduler: "cosine"

# ==================================================
# Model
# ==================================================

model:
  architecture: "cnn_lstm"

  backbone: "mobilenet_v3_small"

  hidden_size: 256

  num_layers: 2

  dropout: 0.3

# ==================================================
# Checkpoints
# ==================================================

checkpoint:
  save_dir: "/content/drive/MyDrive/human_action_recognition/checkpoints/cnn_lstm"
  save_best_only: true

# ==================================================
# Logging
# ==================================================

logging:
  tensorboard_dir: "logs/tensorboard"

  log_interval: 10

# ==================================================
# Evaluation
# ==================================================

evaluation:
  top_k: 5

